const ACTIONS = {
    TOGGLE_RASTER_VISIBILITY: 'TOGGLE_RASTER_VISIBILITY',
    TOGGLE_VECTOR_VISIBILITY: 'TOGGLE_VECTOR_VISIBILITY',
    SET_LAYER_RASTER: 'SET_LAYER_RASTER',
    SET_LAYER_VECTOR: 'SET_LAYER_VECTOR',
    SET_LAYER_GCODE: 'SET_LAYER_GCODE',

    SET_RASTER_REF: 'SET_RASTER_REF',
    SET_VECTOR_REF: 'SET_VECTOR_REF',

    SET_SOURCE_IMAGE: 'SET_SOURCE_IMAGE',

    SET_OUTPUT_SIZE: 'SET_OUTPUT_SIZE',
    SET_SOURCE_SIZE: 'SET_SOURCE_SIZE',
    SET_OUTPUT_TOOL_DIAMETER: 'SET_OUTPUT_TOOL_DIAMETER',
    SET_FEEDRATE_TRAVEL: 'SET_FEEDRATE_TRAVEL',
    SET_FEEDRATE_PLUNGE: 'SET_FEEDRATE_PLUNGE',
    SET_HEIGHT_TRAVEL: 'SET_HEIGHT_TRAVEL',
    SET_HEIGHT_PLUNGE: 'SET_HEIGHT_PLUNGE',

    SET_DOWNLOAD_PACKAGE: 'SET_DOWNLOAD_PACKAGE',
}

export default ACTIONS;