const ACTIONS = {
    TOGGLE_LAYER_VISIBILITY: 'TOGGLE_LAYER_VISIBILITY',
    SET_LAYER_RASTER: 'SET_LAYER_RASTER',

    SET_SOURCE_IMAGE: 'SET_SOURCE_IMAGE',

    SET_OUTPUT_WIDTH: 'SET_OUTPUT_WIDTH',
    SET_OUTPUT_HEIGHT: 'SET_OUTPUT_HEIGHT',
    SET_OUTPUT_TOOL_DIAMETER: 'SET_OUTPUT_TOOL_DIAMETER'
}

export default ACTIONS;